### ISSUE TITLE
Auto launch apps when connecting via bluetooh

### ISSUE THREAD

**Issue by flossokay** [MrMannWood/launcher#3] opened 2021-06-11 18:17 UTC
I, as a user, would like an auto-launch setting in order to streamline the number of clicks I need to do a task.

Example:
Connect to car's bluetooth: open maps and podcast app.

**Comment by MrMannWood** [comment] 2021-06-12 03:26
While I agree that this would be a good feature, the issue is that Bluetooth requires permissions that I don't want to ask for (at least not yet) (location, as of Android 12).

However, there are non-launcher apps that support these types of use-cases. I don't use them, so I can't speak to how effective they are, or if they are killed by battery management systems. But a common and well-regarded one is tasker: https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm&hl=en_US&gl=US

I'll keep this type of feature in mind for the future, but for now I'm closing as "won't do"

**Closed by MrMannWood** 2021-06-12 03:26 UTC
